services:
  - type: web
    name: christian-community-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: AFFILIATE_LINK
        sync: false
      - key: DONATION_LINK
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0